#!/usr/bin/env bash
# Install nginx and start it
apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html  index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
