#!/usr/bin/env bash
# Custom 404 page

apt-get update
apt-get install -y nginx

touch /var/www/html/index.html
touch /var/www/html/error_404.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html/;
    index index.html index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404;
    location = /404 {
        internal;
        try_files /error_404.html =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
