#!/usr/bin/env bash
# Installs and setup firewall

apt-get -y install ufw

apt-get update
apt-get install ufw

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw enable
